<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.github.ralfspoeth.xldr</groupId>
        <artifactId>ia-impl</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>json</artifactId>
    <name>xldr json</name>
    <description>JSON input adapter for xldr, based on Greyson</description>

    <dependencies>
        <dependency>
            <groupId>io.github.ralfspoeth</groupId>
            <artifactId>greyson</artifactId>
        </dependency>
    </dependencies>

</project>
