<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>xldr</artifactId>
        <groupId>com.pd.xldr</groupId>
        <version>${revision}</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>it</artifactId>

    <properties>
        <!-- integration tests only: nothing to publish -->
        <maven.deploy.skip>true</maven.deploy.skip>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.pd.xldr</groupId>
            <artifactId>spec</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.pd.xldr</groupId>
            <artifactId>ldr</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.pd.xldr</groupId>
            <artifactId>app</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.pd.xldr</groupId>
            <artifactId>xml</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.pd.xldr</groupId>
            <artifactId>csv</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.h2database</groupId>
            <artifactId>h2</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

</project>
